# Generated by Django 4.2.4 on 2025-04-25 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('train', 'source', 'destination', 'departure_time')},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('route', 'seat_number')},
        ),
    ]
